# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 03:27
from __future__ import unicode_literals

from django.db import migrations

import os
from sys import path
from project.models import rt;
from django.shortcuts import render, redirect, get_object_or_404
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate
from django.db import transaction
from django.http import HttpResponse, Http404
from django import forms

data_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../../data'));

def get_data(apps, schema_editor):
	#fixture_file = os.path.join(fixture_dir, fixture_filename)

    #fixture = open(fixture_file, 'rb')
	rt_file = os.path.join(data_dir, "routes.csv");
	rts = open(rt_file, 'rb');
	for line in rts:
		rt_no, rt_name = line.split(",");
	RT = rt.objects.filter(rt_no__exact=rt_no);
	if not RT:
		new_rt = rt(rt_no=rt_no,rt_name=rt_name);
		new_rt.save();
	rt.close();



class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
		
    ]
