# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 03:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0002_load_route_and_stop_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='bus_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.BigIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='fav_place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=255)),
                ('place_lat', models.FloatField(default=0.0)),
                ('place_long', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='fav_rt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rt_no', models.CharField(max_length=4)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='rt',
            fields=[
                ('rt_no', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('rt_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='rt_stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir', models.CharField(max_length=255)),
                ('dist', models.FloatField(default=0)),
                ('rt_no', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.rt')),
            ],
        ),
        migrations.CreateModel(
            name='stops',
            fields=[
                ('stop_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('stop_name', models.CharField(max_length=255)),
                ('stop_long', models.FloatField(default=0.0)),
                ('stop_lat', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='rt_stop',
            name='stop_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.stops'),
        ),
    ]
