# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 04:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_load_route_and_stop_data'),
    ]

    operations = [
    ]
